# Generated by Django 4.2.2 on 2024-09-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heirs_holding_app', '0002_alter_registration_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phone_number',
            field=models.CharField(max_length=200),
        ),
    ]
